### ISSUE TITLE
Incompatible versions of log4j and slf4j

### ISSUE THREAD

**Issue by miguel76** [dice-group/LSQ#43]
Launching lsq as standalone from the jar (lsq-cli-2.0.0-SNAPSHOT-jar-with-dependencies.jar) I get the following exception.

```log
Exception in thread "main" java.lang.NoSuchMethodError: 'void org.apache.logging.slf4j.Log4jLoggerFactory.<init>(org.apache.logging.slf4j.Log4jMarkerFactory)'
	at org.apache.logging.slf4j.SLF4JServiceProvider.initialize(SLF4JServiceProvider.java:54)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:153)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:141)
	at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:419)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:405)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:354)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:380)
	at org.aksw.simba.lsq.cli.main.MainCliLsq.<clinit>(MainCliLsq.java:114)
```

There is an incompatibility between the used versions of slf4j (currently 1.8.0-beta4) and Log4j (currently 2.17.1)

**Comment by Aklakan** [comment]
As I mentioned on the PR:

> I aligned slf4j and log4j versions with those of jena 4.7.0 snapshot for now. I only realized afterwards that this is the same slf4j version was proposed by this PR.
